---
sudo: false
dist: xenial
language: ruby
rvm:
  - 2.5.8
matrix:
  include:
    # For now use local checkout of model articulation to use the DA branch. This should be removed once
    # model articulation is released with the bricr model generation file.
    - env: FAVOR_LOCAL_GEMS=1 OPENSTUDIO_VERSION=2.9.1 OPENSTUDIO_SHA=3472e8b799 RUBYLIB=/usr/local/openstudio-2.9.1/Ruby:/usr/Ruby
    - env: FAVOR_LOCAL_GEMS=1 OPENSTUDIO_VERSION=3.0.1 OPENSTUDIO_SHA=09b7c8a554 RUBYLIB=/usr/local/openstudio-3.0.1/Ruby:/usr/Ruby
before_install:
  - gem install bundler
  - bundle -v
  - sudo rm /usr/local/bin/docker-compose
install: 
  - bundle install
before_script:
  - curl -sLO https://raw.githubusercontent.com/NREL/OpenStudio-server/2.9.X-LTS/docker/deployment/scripts/install_openstudio.sh
  - chmod +x install_openstudio.sh
  - sudo ./install_openstudio.sh $OPENSTUDIO_VERSION $OPENSTUDIO_SHA
script:
#  - bundle exec rspec spec/tests/selection_tool_spec.rb  // selection tool is not working with ASHRAE level 1.5 yet
  - bundle exec rspec spec/tests/building_sync_spec.rb
  - bundle exec rspec spec/tests/translator_spec.rb
  - bundle exec rspec spec/tests/epw_test_spec.rb
  - bundle exec rspec spec/tests/model_articulation_test/building_spec.rb
  - bundle exec rspec spec/tests/model_articulation_test/building_section_spec.rb
  - bundle exec rspec spec/tests/model_articulation_test/envelope_system_spec.rb
  - bundle exec rspec spec/tests/model_articulation_test/facility_spec.rb
  - bundle exec rspec spec/tests/model_articulation_test/hvac_system_spec.rb
  - bundle exec rspec spec/tests/model_articulation_test/loads_system_spec.rb
  - bundle exec rspec spec/tests/model_articulation_test/service_hot_water_system_spec.rb
  - bundle exec rspec spec/tests/model_articulation_test/site_spec.rb
#  - bundle exec rspec spec/tests/model_articulation_test/weather_file_download_spec.rb  // fails sometimes due to connection issues, so we exclude it here
  - bundle exec rspec spec/tests/translator_baseline_generation_spec.rb
#  - bundle exec rspec spec/tests/translator_baseline_simulation_spec.rb
  - bundle exec rspec spec/tests/translator_scenario_generation_spec.rb
#  - bundle exec rspec spec/tests/translator_scenario_simulations_spec.rb // this takes too long, had do exclude it from here

