---
sudo: false
dist: xenial
language: ruby
rvm:
  - 2.2.4
matrix:
  include:
    - env: OPENSTUDIO_VERSION=2.8.0 && OPENSTUDIO_SHA=55665635f0 && RUBYLIB=/usr/local/openstudio-2.8.0/Ruby:/usr/Ruby
before_install:
  - gem install bundler -v '~> 1.17'
  - sudo rm /usr/local/bin/docker-compose
install: 
  - bundle install
before_script:
  - curl -sLO https://raw.githubusercontent.com/NREL/OpenStudio-server/develop/docker/deployment/scripts/install_openstudio.sh
  - chmod +x install_openstudio.sh
  - sudo ./install_openstudio.sh $OPENSTUDIO_VERSION $OPENSTUDIO_SHA
script:
  - bundle exec rspec spec/tests/selection_tool_spec.rb
  - bundle exec rspec spec/tests/translator_baseline_generation_spec.rb
  - bundle exec rspec spec/tests/translator_baseline_simulation_spec.rb
#  - bundle exec rake
#  - bundle exec rake openstudio:test_with_openstudio
#  - bundle exec rake
