---
sudo: false
language: ruby
#cache: bundler
rvm:
  - 2.2.4
before_install: 
  - gem install bundler -v '1.17'
  - gem install bundler -v '~> 1.17'
  - sudo rm /usr/local/bin/docker-compose
install: 
  - bundle install
script:
  - ls
  - rspec spec/tests/selection_tool_spec.rb
#  - bundle exec rake 
#  - bundle exec rake openstudio:test_with_openstudio
#  - bundle exec rake   