---
sudo: true
dist: bionic
language: ruby
rvm:
  - 2.5.5
services:
  - docker
env:
  global:
    - SH="docker exec -t os-3.0.1 bash -c "  # shortcut to run a command in the openstudio docker container
before_install:
  - docker pull nrel/openstudio:3.0.1
  - docker images --all
  - docker run -d --name os-3.0.1 -e LANG=C.UTF-8 -v $(pwd):/travis -w /travis nrel/openstudio:3.0.1 tail -f /dev/null
  - docker ps -a
  - pwd
  - ls
  - $SH "env"
  - $SH "echo $LANG"
  - $SH "gem install bundler"
  - $SH "bundle -v"
install:
  - $SH "bundle install --path ."
jobs:
  include:
    - script:
      - $SH "bundle exec rspec spec/tests/translator_write_osm.rb"
      name: "translator.write_osm Test"
    - script:
      - $SH "bundle exec rspec spec/tests/translator_run_baseline_osm.rb"
      name: "translator.run_baseline_osm with no epw file provided Tests"
    - script:
      - $SH "bundle exec rspec spec/tests/translator_gather_save_results_spec.rb"
      name: "translator.translator_gather_save_results_spec Tests"
    - script:
      - $SH "bundle exec rspec spec/tests/model_articulation_test/building_section_spec.rb"
      - $SH "bundle exec rspec spec/tests/model_articulation_test/building_spec.rb"
      - $SH "bundle exec rspec spec/tests/model_articulation_test/envelope_system_spec.rb"
      - $SH "bundle exec rspec spec/tests/model_articulation_test/facility_spec.rb"
      - $SH "bundle exec rspec spec/tests/model_articulation_test/hvac_system_spec.rb"
      - $SH "bundle exec rspec spec/tests/model_articulation_test/loads_system_spec.rb"
      - $SH "bundle exec rspec spec/tests/model_articulation_test/service_hot_water_system_spec.rb"
      - $SH "bundle exec rspec spec/tests/model_articulation_test/site_spec.rb"
      # - $SH "bundle exec rspec spec/tests/model_articulation_test/weather_file_download_spec.rb"  // fails sometimes due to connection issues, so we exclude it here
      name: "Model Articulation Tests"
    - script:
      - travis_wait 50 $SH "bundle exec rspec spec/tests/translator_spec.rb"
      name: "Translator Spec"
    - script:
      - travis_wait 40 $SH "bundle exec rspec spec/tests/model_articulation_test/hospital_occupancy_type_spec.rb"
      name: "Hospital Occupancy Type Spec"
    - script:
      - $SH "bundle exec rspec spec/tests/model_articulation_test/occupancy_types_spec.rb"
      name: "Occupancy Types Spec"
    - script:
      - $SH "bundle exec rspec spec/tests/translator_baseline_generation_spec.rb"
      - $SH "bundle exec rspec spec/tests/translator_scenario_generation_spec.rb"
      name: "Translator Generation Specs"
    - script:
      - $SH "bundle exec rspec spec/tests/translator_baseline_simulation_spec.rb"
      name: "Translator Baseline Simulation Spec"
    - script:
      - $SH "bundle exec rspec spec/tests/translator_scenario_simulations_spec.rb"
      name: "Translator Scenario Simulation Spec"
    - script:
      - $SH "bundle exec rspec spec/tests/building_sync_spec.rb"
      - $SH "bundle exec rspec spec/tests/epw_test_spec.rb"
      # - $SH "bundle exec rspec spec/tests/selection_tool_spec.rb"  # selection tool is not working with ASHRAE level 1.5 yet
      name: "Other Specs"
