name: ci

on:
  pull_request:
  push:

env:
  SH: 'docker exec -t os-3.0.1 bash -c '

jobs:
  setup_container:
    name: Setup Container
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Docker
      run: |
        docker pull nrel/openstudio:3.0.1
        docker images --all
        docker run -d --name os-3.0.1 -e LANG=C.UTF-8 -v $(pwd):/travis -w /travis nrel/openstudio:3.0.1 tail -f /dev/null
        docker ps -a
        pwd
        ls
        $SH "mkdir /test"
        $SH "cp -R /travis/* /test/"
        $SH "cd /test"
        $SH "env"
        $SH "echo $LANG"
        $SH "gem install bundler"
        $SH "bundle -v"
        $SH "ls"
        $SH "bundle install --path ."
    - name: Save Docker
      run: |
        docker commit -p $(docker ps -l -q) os-3.0.1 
        docker save -o container.tar os-3.0.1
    - name: Upload Container
      uses: actions/upload-artifact@v2
      with:
        name: container
        path: container.tar

  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: setup_container
    steps:
    - name: Download Container
      uses: actions/download-artifact@v2
      with:
        name: container
    - name: Start Container
      run: |
        docker load -i container.tar
        docker run -d --name os-3.0.1 -w /test os-3.0.1
    - name: Model Articulation Tests
      run: |
        $SH "bundle exec rspec spec/tests/model_articulation_test/building_section_spec.rb"
        $SH "bundle exec rspec spec/tests/model_articulation_test/building_spec.rb"
        $SH "bundle exec rspec spec/tests/model_articulation_test/envelope_system_spec.rb"
        $SH "bundle exec rspec spec/tests/model_articulation_test/facility_spec.rb"
        $SH "bundle exec rspec spec/tests/model_articulation_test/hvac_system_spec.rb"
        $SH "bundle exec rspec spec/tests/model_articulation_test/loads_system_spec.rb"
        $SH "bundle exec rspec spec/tests/model_articulation_test/lighting_system_type_spec.rb"
        $SH "bundle exec rspec spec/tests/model_articulation_test/service_hot_water_system_spec.rb"
        $SH "bundle exec rspec spec/tests/model_articulation_test/site_spec.rb"
        # $SH "bundle exec rspec spec/tests/model_articulation_test/weather_file_download_spec.rb"  // fails sometimes due to connection issues, so we exclude it here
