name: Continuous Integration

on:
  pull_request:
  push:

jobs:
  model_articulation_tests:
    name: Model Articulation Tests
    container: nrel/openstudio:3.0.1
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup
      run: |
        gem install bundler
        bundle install
    - name: Model Articulation Tests
      run: |
        bundle exec rspec spec/tests/model_articulation_test/building_section_spec.rb
        bundle exec rspec spec/tests/model_articulation_test/building_spec.rb
        bundle exec rspec spec/tests/model_articulation_test/envelope_system_spec.rb
        bundle exec rspec spec/tests/model_articulation_test/facility_spec.rb
        bundle exec rspec spec/tests/model_articulation_test/hvac_system_spec.rb
        bundle exec rspec spec/tests/model_articulation_test/loads_system_spec.rb
        bundle exec rspec spec/tests/model_articulation_test/lighting_system_type_spec.rb
        bundle exec rspec spec/tests/model_articulation_test/service_hot_water_system_spec.rb
        bundle exec rspec spec/tests/model_articulation_test/site_spec.rb
        # bundle exec rspec spec/tests/model_articulation_test/weather_file_download_spec.rb  // fails sometimes due to connection issues, so we exclude it here
    - name: Model Articulation Hospital Occupancy Type Spec
      run: bundle exec rspec spec/tests/model_articulation_test/hospital_occupancy_type_spec.rb
    - name: Model Articulation Occupancy Types Spec
      run: bundle exec rspec spec/tests/model_articulation_test/occupancy_types_spec.rb

  translator_tests:
    name: Model Articulation Tests
    container: nrel/openstudio:3.0.1
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup
      run: |
        gem install bundler
        bundle install
    - name: Translator Spec
      run: bundle exec rspec spec/tests/translator_spec.rb
    - name: Translator Sizing Run Spec
      run: bundle exec rspec spec/tests/translator_sizing_run_spec.rb
    - name: Translator Perform SR and Baseline Simulations Spec
      run: bundle exec rspec spec/tests/translator_baseline_simulation_spec.rb
    - name: Translator Perform SR and Baseline Simulations, Gather and Save Results Spec
      run: bundle exec rspec spec/tests/translator_baseline_gather_save_spec.rb
    - name: Translator Generation Specs
      run: bundle exec rspec spec/tests/translator_scenario_generation_spec.rb
    - name: Translator Scenario Simulation Spec
      run: bundle exec rspec spec/tests/translator_scenario_simulations_spec.rb

  report_and_scenario_tests:
    name: Report and Scenario Tests
    container: nrel/openstudio:3.0.1
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup
      run: |
        gem install bundler
        bundle install
    - name: Report and Scenario Related Specs
      run: |
        bundle exec rspec spec/tests/report_spec.rb
        bundle exec rspec spec/tests/utility_spec.rb
        bundle exec rspec spec/tests/scenario_spec.rb
        bundle exec rspec spec/tests/time_series_spec.rb
        bundle exec rspec spec/tests/resource_use_spec.rb
        bundle exec rspec spec/tests/all_resource_total_spec.rb
    - name: WorkflowMaker Spec
      run: bundle exec rspec spec/tests/workflow_maker_spec.rb

  other_specs:
    name: Other Specs
    container: nrel/openstudio:3.0.1
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup
      run: |
        gem install bundler
        bundle install
    - name: Other Specs
      run: |
        bundle exec rspec spec/tests/building_sync_spec.rb
        bundle exec rspec spec/tests/epw_test_spec.rb
        bundle exec rspec spec/tests/constants_spec.rb
        bundle exec rspec spec/tests/generator_spec.rb
        bundle exec rspec spec/tests/helper_spec.rb
        bundle exec rspec spec/tests/xml_get_set_spec.rb
	# bundle exec rspec spec/tests/selection_tool_spec.rb  # selection tool is not working with ASHRAE level 1.5 yet